### ISSUE TITLE
How do I use this snippet?

### ISSUE THREAD

**Issue by cutiepatootiebear** [shaman-apprentice/vs-code-html5-skelton#1]
Is there a keyword shortcut? Thanks

**Comment by shaman-apprentice** [comment]
After you have installed [this extention](https://marketplace.visualstudio.com/items?itemName=shaman-apprentice.html5-skelton), you can type "_html-skelton_" within an html file and select the suggestion. That will enter the template at the position, where you typed it. 

It is also described in the [documentation for snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets)

**Comment by shaman-apprentice** [comment]
Feel free to ask any further question / re-open or create a new one ;)
